import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Geist, Inter } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-jakarta-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        jakartaSans.variable,
        inter.variable,
        "font-sans",
        geist.variable,
      )}
    >
      <body className="">{children}</body>
    </html>
  );
}
