import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/sidebar";
import Navbar from "@/components/navbar";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        jakartaSans.variable,
        "font-sans",
        geist.variable,
      )}
    >
      <body className="h-screen flex">
        <Sidebar />
        <div className="flex flex-col flex-1 ml-64">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
